export const UI = {};

export function initDOMCache() {
    const ids = [
        'val-omega-t', 'val-omega-p', 'val-ratio', 'val-phase-ratio', 'val-ergodic', 'val-schumann',
        'row-omega-t', 'row-omega-p', 'row-ratio', 'row-phase-ratio', 'row-ergodic', 'row-schumann',
        'val-torus-formed', 'val-irrational', 'row-torus-formed', 'row-irrational',
        'val-metric-mode', 'row-metric-mode',
        'val-major-radius', 'row-major-radius',
        'val-minor-radius', 'row-minor-radius',
        'val-gaussian-range', 'row-gaussian-range',
        'val-mean-range', 'row-mean-range',
        'val-curvature-asymmetry', 'row-curvature-asymmetry',
        'val-curvature-regions', 'row-curvature-regions',
        'val-geometry-confidence', 'row-geometry-confidence',
        'torus-metric-note',
        'val-firing', 'val-cluster', 'val-phi', 'val-coherence', 'val-attractor-id', 'val-attractor-sim', 'val-arousal',
        'row-firing', 'row-cluster', 'row-phi', 'row-coherence', 'row-attractor-id', 'row-attractor-sim', 'row-arousal',
        'val-branching', 'row-branching', 'sigma-bar-fill', 'val-homeo', 'row-homeo', 'val-tension', 'row-tension', 'val-touch', 'row-touch',
        'val-touch-active', 'row-touch-active', 'val-raw-touch', 'row-raw-touch',
        'val-touch-onset', 'row-touch-onset', 'val-touch-offset', 'row-touch-offset', 'val-touch-novelty', 'row-touch-novelty',
        'val-sound-level', 'row-sound-level',
        'val-sound-delta', 'row-sound-delta',
        'val-sound-low', 'row-sound-low',
        'val-sound-mid', 'row-sound-mid',
        'val-sound-high', 'row-sound-high',
        'val-sound-novelty', 'row-sound-novelty',
        'val-sound-persistence', 'row-sound-persistence',
        'val-sound-active', 'row-sound-active',
        'val-baseline', 'row-baseline', 'val-residue', 'row-residue',
        'val-local-pred-error', 'row-local-pred-error',
        'val-pre-a', 'row-pre-a', 'val-pre-b', 'row-pre-b', 'val-pre-c', 'row-pre-c', 'val-pre-d', 'row-pre-d', 'val-pre-e', 'row-pre-e', 'val-total', 'row-total',
        'val-complex-mode', 'row-complex-mode',
        'val-complex-max-amplitude', 'row-complex-max-amplitude',
        'val-complex-average-amplitude', 'row-complex-average-amplitude',
        'val-complex-phase-coherence', 'row-complex-phase-coherence',
        'val-complex-phase-gradient', 'row-complex-phase-gradient',
        'val-complex-vortex-count', 'row-complex-vortex-count',
        'val-complex-positive-charge', 'row-complex-positive-charge',
        'val-complex-negative-charge', 'row-complex-negative-charge',
        'val-complex-total-charge', 'row-complex-total-charge',
        'val-complex-average-vortex-confidence', 'row-complex-average-vortex-confidence',
        'val-complex-nan', 'row-complex-nan',
        'val-complex-amplitude-clamp', 'row-complex-amplitude-clamp',
        'val-complex-phase-unwrap', 'row-complex-phase-unwrap',
        'system-state-badge', 'intro-guide',
        // PR7: Touch pattern
        'val-touch-duration', 'row-touch-duration',
        'val-touch-velocity', 'row-touch-velocity',
        'val-touch-repeat',   'row-touch-repeat',
        'val-touch-dominant', 'row-touch-dominant',
        'val-score-tap',      'row-score-tap',
        'val-score-repeat',   'row-score-repeat',
        'val-score-hold',     'row-score-hold',
        'val-score-stroke',   'row-score-stroke',
        'val-rewrite-tendency', 'row-rewrite-tendency',
        'val-rewrite-pressure', 'row-rewrite-pressure',
        'val-rewrite-load',     'row-rewrite-load',
        'val-prior-bias',       'row-prior-bias',
        'val-last-rewrite',     'row-last-rewrite',
        'val-noise-path',       'row-noise-path',
        'val-noise-mag',        'row-noise-mag',
        'val-dormant-nodes',    'row-dormant-nodes',
        'val-dormant-wakes',    'row-dormant-wakes',
        'val-dormant-pressure', 'row-dormant-pressure',
        'val-dormant-events',   'row-dormant-events',
        'val-mode-state',       'row-mode-state',
        'val-wake-drive',       'row-wake-drive',
        'val-sleep-pressure',   'row-sleep-pressure',
        'val-dream-pressure',   'row-dream-pressure',
        'val-last-mode-change', 'row-last-mode-change',
        'val-dream-replay',     'row-dream-replay',
        'val-energy',           'row-energy',
        'val-stability',        'row-stability',
        'val-overload',         'row-overload',
        'val-rest-drive',       'row-rest-drive',
        'val-orienting-drive',  'row-orienting-drive',
        'val-action-state',     'row-action-state',
        'val-action-pulse',     'row-action-pulse',
        'val-action-direction', 'row-action-direction',
        'val-last-touch-direction', 'row-last-touch-direction',
        // Phase B2: light sensory
        'val-light-level',       'row-light-level',
        'val-light-delta',       'row-light-delta',
        'val-light-novelty',     'row-light-novelty',
        'val-light-persistence', 'row-light-persistence',
        'val-light-active',      'row-light-active',
        // Phase B2: motion sensory
        'val-motion-level',       'row-motion-level',
        'val-motion-delta',       'row-motion-delta',
        'val-motion-novelty',     'row-motion-novelty',
        'val-motion-persistence', 'row-motion-persistence',
        'val-motion-active',      'row-motion-active',
        // Phase B2: time sensory
        'val-time-phase',        'row-time-phase',
        'val-time-level',        'row-time-level',
        'val-time-persistence',  'row-time-persistence',
        'val-time-active',       'row-time-active',
        'val-bl-arousal-level',  'row-bl-arousal-level',
        'val-bl-awareness-window', 'row-bl-awareness-window',
        'val-bl-salience-openness', 'row-bl-salience-openness',
        'val-bl-foreground-pressure', 'row-bl-foreground-pressure',
        'val-bl-rest-depth', 'row-bl-rest-depth',
        'val-bl-hyperreactivity', 'row-bl-hyperreactivity',
        'val-bl-settling-window', 'row-bl-settling-window',
        'val-trace-strength', 'row-trace-strength',
        'val-recurrence-weight', 'row-recurrence-weight',
        'val-salience-residue', 'row-salience-residue',
        'val-trace-replay-readiness', 'row-trace-replay-readiness',
        'val-trace-replay-suppression', 'row-trace-replay-suppression',
        'val-recent-pattern-weight', 'row-recent-pattern-weight',
        'val-settling-residue', 'row-settling-residue',
        'val-recovery-linked-residue', 'row-recovery-linked-residue',
        // Phase E1: hierarchical torus
        'val-subtori-count',      'val-subtorus-size',
        'val-upper-size',         'val-sub-mean-activity',
        'val-sub-mean-arousal',   'val-sub-mean-sigma',
        'val-sub-mean-phi',       'val-upper-mean-activity',
        'val-upper-arousal',      'val-upper-sigma',
        'val-upper-phi',
        // Phase 1: Ongoingness observer
        'val-mean-activity',      'row-mean-activity',
        'val-activity-variance',  'row-activity-variance',
        'val-collapse-rate',      'row-collapse-rate',
        'val-saturation-rate',    'row-saturation-rate',
        'val-quiet-floor',        'row-quiet-floor',
        'val-ignition-count',     'row-ignition-count',
        // Phase 3: Recovery observer
        'val-recovery-pressure',      'row-recovery-pressure',
        'val-relaxation-level',       'row-relaxation-level',
        'val-stabilization-pull',     'row-stabilization-pull',
        'val-recovery-collapse-risk', 'row-recovery-collapse-risk',
        'val-boundary-repair-pressure', 'row-boundary-repair-pressure',
        'val-self-preservation-drive', 'row-self-preservation-drive',
        'val-overload-drain',         'row-overload-drain',
        'val-recovery-trajectory',    'row-recovery-trajectory',
        'val-collapse-mode',          'row-collapse-mode',
        // W2: Actuation Pulse observer
        'val-actuation-channel', 'row-actuation-channel',
        'val-actuation-intensity', 'row-actuation-intensity',
        'val-actuation-coherence', 'row-actuation-coherence',
        'val-actuation-rhythm', 'row-actuation-rhythm',
        'val-actuation-locality', 'row-actuation-locality',
        'val-actuation-recovery-linked', 'row-actuation-recovery-linked',
        'val-actuation-boundary-linked', 'row-actuation-boundary-linked',
        'val-actuation-trace-linked', 'row-actuation-trace-linked',
        'val-actuation-output-readiness', 'row-actuation-output-readiness',
        'val-actuation-generated-count', 'row-actuation-generated-count',
        'val-actuation-null-count', 'row-actuation-null-count',
        // S4: Medium Profile observer
        'val-medium-delay-average', 'row-medium-delay-average',
        'val-medium-delay-min', 'row-medium-delay-min',
        'val-medium-delay-max', 'row-medium-delay-max',
        'val-medium-delay-variance', 'row-medium-delay-variance',
        'val-medium-delay-stable-window', 'row-medium-delay-stable-window',
        'val-medium-delay-unstable-score', 'row-medium-delay-unstable-score',
        'val-medium-delay-delayed-echo', 'row-medium-delay-delayed-echo',
        'val-medium-echo-strength', 'row-medium-echo-strength',
        'val-medium-echo-decay', 'row-medium-echo-decay',
        'val-medium-echo-persistence', 'row-medium-echo-persistence',
        'val-medium-echo-saturation', 'row-medium-echo-saturation',
        'val-medium-visual-residue', 'row-medium-visual-residue',
        'val-medium-force-residue', 'row-medium-force-residue',
        'val-medium-return-coupling', 'row-medium-return-coupling',
        'val-medium-world-resistance', 'row-medium-world-resistance',
        'val-medium-boundary-resistance', 'row-medium-boundary-resistance',
        'val-medium-return-attenuation', 'row-medium-return-attenuation',
        'val-medium-absorption', 'row-medium-absorption',
        'val-medium-transmission-ratio', 'row-medium-transmission-ratio',
        'val-medium-resistance-balance', 'row-medium-resistance-balance',
        'val-medium-resistance-variance', 'row-medium-resistance-variance',
        'val-medium-profile-confidence', 'row-medium-profile-confidence',
    ];
    ids.forEach(id => { UI[id] = document.getElementById(id); });
}

export function updateUIRow(rowEl, valEl, value, isMet) {
    if(!rowEl || !valEl) return;
    valEl.innerText = value;
    if (isMet) { rowEl.classList.remove('text-white/70'); rowEl.classList.add('text-cyan-300'); }
    else       { rowEl.classList.remove('text-cyan-300'); rowEl.classList.add('text-white/70'); }
}
